# Generated by Django 4.2.7 on 2023-11-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('cep', models.CharField(verbose_name='CEP')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero_casa', models.CharField(verbose_name='Número ')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=50, verbose_name='Assunto')),
                ('data', models.DateTimeField(verbose_name='Data da postagem')),
                ('conteudo', models.TextField(max_length=500, verbose_name='Sobre a postagem')),
                ('turma', models.IntegerField(choices=[(1, '6° Ano'), (2, '7° Ano'), (3, '8° Ano'), (4, '9° Ano'), (5, 'Todas')], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('matricula', models.CharField(max_length=50, verbose_name='Número Matricula')),
                ('email', models.EmailField(max_length=11, unique=True, verbose_name='Email')),
                ('cargo', models.IntegerField(choices=[(1, 'Diretor'), (2, 'Professor')], default=2)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='postagem',
            name='responsavel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.user'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.user'),
        ),
    ]
