# Generated by Django 4.2.6 on 2023-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(default='Avisos Gerais', max_length=50),
        ),
    ]
