# Generated by Django 4.2.6 on 2023-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
