# Generated by Django 4.2.6 on 2023-11-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_alter_card_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='category',
            new_name='turma',
        ),
    ]
