# Generated by Django 4.2.6 on 2023-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_rename_category_card_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
